services:
  webserver:
    container_name: paveguard-webserver
    build:
      context: ./paveguard-webserver.dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestjs
    depends_on:
      - mongo
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nestjs
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance

volumes:
  mongo_data: